import re

file_path = r"c:\Users\ELİF NAZ\Desktop\PROJELER\ai-chaos-platform\staj_defteri.md"
with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

replacements = {
    r"Tüm bu veri akışını, yapay zeka analizlerini ve kaos yönetim panellerini görselleştirmek için Streamlit kütüphanesini araştırmaya başladım\. Python tabanlı web arayüzlerinin hızlı prototipleme avantajlarını inceledim\. Dashboard bileşenlerinin \(metrik kartları, grafik alanları, butonlar\) mimari yerleşimini kağıt üzerinde planladım\.": 
    "Tüm bu veri akışını, yapay zeka analizlerini ve kaos yönetim panellerini görselleştirmek için veri bilimi ve makine öğrenmesi projelerinde sıklıkla tercih edilen Streamlit kütüphanesini araştırmaya başladım. Geleneksel web geliştirme süreçlerinin getirdiği HTML, CSS ve JavaScript karmaşasından kurtularak, sadece Python kodları ile interaktif web arayüzleri oluşturabilmenin hızlı prototipleme avantajlarını detaylı bir şekilde inceledim. Projenin izleme paneli (Dashboard) üzerinde yer alacak bileşenlerin (anlık CPU/RAM metrik kartları, tarihsel verileri gösteren çizgi grafikler ve anomali uyarı logları) mimari yerleşimini, kullanıcı deneyimini (UX) ön planda tutarak kağıt üzerinde taslaklar halinde planladım.",

    r"Streamlit kullanarak dashboard/app\.py uygulamasını kodlamaya başladım\. Veritabanındaki son metrikleri anlık olarak okuyan ve st\.metric ile st\.line_chart bileşenlerini kullanarak CPU ve RAM kullanım oranlarını dinamik grafiklere döken arayüzü oluşturdum\. Sayfanın 15 saniyede bir otomatik yenilenmesini \(st\.rerun / st_autorefresh\) sağlayan mekanizmayı ekledim\.":
    "Streamlit kütüphanesini kullanarak `dashboard/app.py` uygulamasını fiili olarak kodlamaya başladım. SQLite veritabanındaki `metrics` tablosuna bağlanan ve son kaydedilen metrikleri anlık olarak sorgulayan bir veri erişim katmanı yazdım. Çekilen bu verileri ekranda görselleştirmek için `st.metric` ile anlık değer kartları ve `st.line_chart` bileşenlerini kullanarak CPU ile RAM kullanım oranlarının zaman içindeki değişimini dinamik grafiklere döken bir arayüz oluşturdum. İzleme ekranının gerçekten 'canlı' (real-time) olabilmesi adına sayfanın 15 saniyede bir veritabanından yeni verileri alarak otomatik yenilenmesini sağlayan `st_autorefresh` mekanizmasını sisteme entegre ettim.\n\n```python\nimport streamlit as st\nimport pandas as pd\nfrom streamlit_autorefresh import st_autorefresh\n\n# Sayfayı her 15 saniyede bir yenile\ncount = st_autorefresh(interval=15000, key=\"dashboard_autorefresh\")\n\nst.set_page_config(page_title=\"AI Chaos Platform\", layout=\"wide\")\nst.title(\"Gerçek Zamanlı Sistem Metrikleri\")\n\n# Veritabanından veri çekme (Simülasyon)\ndf = get_latest_metrics(limit=50)\n\ncol1, col2 = st.columns(2)\nwith col1:\n    st.metric(\"Anlık CPU Kullanımı\", f\"{df['cpu_percent'].iloc[-1]}%\", delta=\"-1.2%\")\nwith col2:\n    st.metric(\"Anlık RAM Kullanımı\", f\"{df['ram_percent'].iloc[-1]}%\", delta=\"+0.8%\")\n\nst.line_chart(df.set_index('timestamp')[['cpu_percent', 'ram_percent']])\n```\n*Şekil 8 - Streamlit Canlı Metrik Gösterimi Kod Yapısı*",

    r"Streamlit arayüzüne sistem yöneticilerinin uzaktan kaos senaryolarını tetikleyebileceği interaktif kontrol butonları ekledim\. \"Bellek Sızıntısı Başlat\" ve \"CPU Yükü Bindir\" butonlarına basıldığında FastAPI üzerindeki ilgili kaos endpoint'lerine HTTP POST isteği gönderen tetikleyici fonksiyonlar yazdım\.":
    "Streamlit arayüzüne, sistem yöneticilerinin sadece verileri izlemekle kalmayıp aynı zamanda sisteme müdahale edebileceği, uzaktan kaos senaryolarını tetikleyebileceği interaktif bir kontrol paneli (Control Panel) ekledim. Bu panelde 'Bellek Sızıntısı Başlat', 'CPU Yükü Bindir' ve 'Sistemi Normale Döndür' gibi işlevsel butonlar tasarladım. Bu butonlara tıklandığında, arka planda `requests` kütüphanesi aracılığıyla FastAPI sunucusundaki Chaos Engineering endpoint'lerine (`/chaos/start-leak`, `/chaos/start-cpu`) HTTP POST istekleri gönderen senkronize tetikleyici fonksiyonlar yazdım. Bu sayede, kaosu arayüzden yönetilebilir hale getirdim.",

    r"Dashboard arayüzüne PyTorch anomali tahmin modelinin çıktısını ve LLM tarafından üretilen JSON tabanlı çözüm önerilerini şık kartlar halinde basacak UI bileşenleri ekledim\. Sistem normal çalışırken yeşil, anomali tespit edildiğinde ise kırmızı alarm veren dinamik tema ve uyarı mekanizmaları tasarladım\.":
    "Dashboard arayüzüne, PyTorch derin öğrenme modelinden dönen anomali olasılık skorunu ve Qwen 2.5 LLM modelinin ürettiği yapılandırılmış JSON tabanlı çözüm önerilerini (kök neden analizi ve aksiyon adımları) kullanıcı dostu, şık metin kartları halinde render edecek UI bileşenleri ekledim. Görsel iletişimi güçlendirmek adına, sistem metrikleri normal seyrettiğinde arayüzdeki durum göstergelerinin yeşil renkte (Normal) yanmasını, bir anomali tespit edildiğinde ise otomatik olarak kırmızı renge (Kritik Risk) bürünerek sesli ve görsel alarm veren dinamik bir tema yapısı tasarladım.",

    r"Ajan ile sunucu arasındaki veri iletim performansını artırmak amacıyla kod tabanında refactoring yaptım\. FastAPI arka plan görevleri ile SQLite yazma işlemlerinde olası çakışmaları \(database is locked hatalarını\) önlemek için bağlantı havuzu \(connection pooling\) ve istisna yakalama \(try-except\) bloklarını güçlendirdim\.":
    "Yüksek veri akışı altında sistemin stabilitesini korumak ve Agent ile FastAPI sunucusu arasındaki veri iletim performansını maksimize etmek amacıyla kod tabanında detaylı bir refactoring (kod iyileştirme) çalışması yürüttüm. Asenkron olarak çalışan FastAPI arka plan görevlerinin, eşzamanlı olarak SQLite veritabanına yazmaya çalışması sonucu ortaya çıkabilecek 'database is locked' kilitlenme hatalarını derinlemesine inceledim. Bu kilitlenmeleri önlemek için veritabanı bağlantılarını daha verimli yöneten connection pooling (bağlantı havuzu) yapılandırmalarını devreye aldım ve try-except-finally blokları ile istisna yakalama (exception handling) mekanizmalarını baştan aşağı güçlendirdim.",

    r"Ajanın sunucuya erişemediği durumlarda \(ağ kopması vb\.\) veri kaybını önlemek için ajan tarafına yerel önbellekleme \(local buffering / retry mechanism\) mekanizması ekledim\. Sunucu tarafında ise tüm API katmanında kapsamlı bir global exception handler yapısı kurarak istemciye anlamlı hata mesajları dönülmesini sağladım\.":
    "Gerçek dünya senaryolarında sistem bileşenleri arasındaki iletişimin her zaman kusursuz olmayacağı gerçeğinden yola çıkarak, Agent'ın FastAPI sunucusuna erişemediği durumlarda (anlık ağ kesintileri veya sunucu çökmeleri) oluşabilecek veri kaybını önlemek için ajan tarafında yerel bir önbellekleme (local buffering) ve üstel geri çekilme (exponential backoff) prensibiyle çalışan bir yeniden deneme (retry) mekanizması kodladım. Sunucu tarafında ise, uygulamanın beklenmedik durumlarda çökmesini engelleyerek kullanıcılara ve diğer servislere anlamlı, standart JSON hata mesajları dönülmesini sağlayan merkezi bir global exception handler (global hata yakalayıcı) mimarisi inşa ettim.",

    r"FinTech sistemlerinin güvenlik gereksinimleri göz önünde bulundurularak ajan ile sunucu arasındaki iletişimi korumak amacıyla Bearer Token / API Key doğrulama mekanizmasını FastAPI'ye entegre ettim\. Yetkisiz isteklerin veritabanına erişmesini engelleyen güvenlik katmanını \(Depends injection\) tamamladım\.":
    "Özellikle FinTech ve bankacılık gibi kritik sistemlerin temel taşı olan güvenlik gereksinimlerini projeme entegre etmek için kolları sıvadım. Agent uygulamasının FastAPI sunucusuna metrik gönderirken kimliğini ispatlaması amacıyla 'Bearer Token' ve 'API Key' tabanlı bir kimlik doğrulama (Authentication) mekanizması tasarladım. FastAPI'nin `Depends` ve `security` modüllerini kullanarak Dependency Injection (bağımlılık enjeksiyonu) mantığıyla tüm kritik endpoint'lerin önüne bir güvenlik katmanı çektim. Böylece yetkisiz isteklerin ve olası kötü niyetli veri manipülasyonlarının sisteme sızmasını tamamen engelledim.",

    r"Yazdığım tüm modüllerin \(Agent, FastAPI Server, SQLite DB, PyTorch Model, LLM Servisi, Streamlit Dashboard\) bir arada hatasız çalışıp çalışmadığını test etmek için kapsamlı senaryo testleri koştum\. Kaos butonuna basıldığından veritabanına yazılmasına, oradan yapay zekaya gitmesine ve dashboard'da uyarı vermesine kadar olan zinciri test ettim\.":
    "Geliştirdiğim birbirinden bağımsız mikro servis benzeri tüm modüllerin (Python Agent, FastAPI Server, SQLite Veritabanı, PyTorch Derin Öğrenme Modeli, Ollama LLM Servisi ve Streamlit Dashboard) entegre bir biçimde, hatasız olarak haberleşip haberleşmediğini doğrulamak için uçtan uca (End-to-End) sistem entegrasyon testleri gerçekleştirdim. Dashboard üzerinden 'Kaos Başlat' butonuna basıldığı andan itibaren, FastAPI'nin bunu algılaması, donanımda sızıntı başlatması, ajanın bunu yakalayıp veritabanına iletmesi, PyTorch'un anomaliyi tespit edip LLM'in çözüm üretmesi ve bu çözümün tekrar arayüze yansımasına kadar uzanan tam tur veri zincirini (pipeline) adım adım debug ederek test ettim.",

    r"Sistemin yüksek yük altında vereceği tepkileri ölçmek için locust veya Python betikleri yardımıyla eşzamanlı HTTP istekleri simüle ettim\. FastAPI sunucusunun saniyede kaç adet metrik paketini hatasız işleyebileceğini test ederek olası darboğazları tespit ettim ve optimize ettim\.":
    "Geliştirdiğim sistemin gerçek bir üretim (production) ortamında, yüksek trafik ve stres altında nasıl bir davranış sergileyeceğini ölçmek için performans ve yük benzetim (Load Testing) çalışmaları yaptım. Sektör standardı araçlardan biri olan `Locust` kütüphanesini kullanarak yüzlerce sanal sistem ajanı (virtual user) oluşturdum ve bu ajanların eşzamanlı olarak FastAPI sunucusuna sürekli HTTP POST istekleri atmasını simüle ettim. Bu testler sonucunda sunucunun saniyede kaç istek (Requests Per Second - RPS) işleyebildiğini ölçtüm, veritabanı yazma kilitlenmeleri gibi darboğazları (bottleneck) tespit ettim ve asenkron I/O optimizasyonlarıyla bu sorunları giderdim.",

    r"Proje kod tabanının PEP 8 standartlarına uygunluğunu denetlemek amacıyla flake8 ve black araçlarını çalıştırdım\. Kod içerisindeki gereksiz boşlukları, uzun satırları ve eksik docstring dokümantasyonlarını temizleyerek yazılım kalitesini \(code cleanliness\) en üst düzeye çıkardım\.":
    "Kurumsal yazılım geliştirme pratiklerinin en önemlilerinden biri olan statik kod analizi (Static Code Analysis) ve kod standartlaştırması üzerine yoğunlaştım. Projedeki tüm Python dosyalarının endüstri standardı olan PEP 8 kurallarına harfiyen uymasını sağlamak amacıyla kod tabanı üzerinde `flake8` linter'ını ve otomatik formatlayıcı olan `black` araçlarını koştum. Kod içerisinde unutulmuş kullanılmayan değişkenleri (unused imports), gereksiz boşlukları, 80 karakteri aşan aşırı uzun satırları düzenledim ve sınıfların/fonksiyonların başına kapsamlı docstring (belgelendirme metinleri) ekleyerek yazılım kalitesini (Code Quality) ve okunabilirliğini en üst düzeye taşıdım.",

    r"Projenin GitHub üzerinde profesyonel bir şekilde sunulabilmesi için kapsamlı bir README\.md dosyası hazırladım\. Projenin mimari şemasını, kurulum adımlarını \(pip install -r requirements\.txt\), FastAPI sunucusunun nasıl ayağa kaldırılacağını, ajan uygulamasının nasıl çalıştırılacağını ve Streamlit dashboard komutlarını detaylıca dokümante ettim\.":
    "Geliştirdiğim platformun diğer yazılımcılar ve ekip arkadaşları tarafından rahatça anlaşılıp çalıştırılabilmesi için, projenin vitrini niteliğinde olan çok kapsamlı bir `README.md` dokümantasyonu hazırladım. Bu belge içerisinde projenin teknik mimari şemasını (Architecture Diagram), kullanılan teknoloji yığınını (Tech Stack), sanal ortam kurulumu ve bağımlılık yükleme adımlarını (`pip install -r requirements.txt`) adım adım açıkladım. Ayrıca FastAPI sunucusunun, veri toplayıcı ajan betiklerinin, Ollama yerel model servisinin ve son olarak Streamlit dashboard'unun sırasıyla nasıl ayağa kaldırılacağına dair konsol komutlarını detaylıca yazarak profesyonel bir proje teslim belgesi oluşturdum.",

    r"PyTorch ile eğittiğim anomali tespit modelinin başarım oranını \(accuracy ve f1-score\) artırmak için hiperparametre optimizasyonu \(Learning Rate ve Katman Boyutları\) yaptım\. Farklı epoch ve batch size kombinasyonlarını deneyerek modelin yanlış alarm oranını \(False Positive Rate\) en aza indiren en iyi ağırlık setini belirledim\.":
    "Daha önce eğittiğim temel PyTorch çok katmanlı algılayıcı (MLP) modelinin istatistiksel başarım oranını (Accuracy, Precision, Recall ve F1-Score) endüstri standartlarına çıkarmak için detaylı bir Hiperparametre Optimizasyonu (Hyperparameter Tuning) süreci yürüttüm. Makine öğrenmesinde son derece kritik olan öğrenme katsayısı (Learning Rate), gizli katman (hidden layer) nöron sayıları, mini-batch boyutları ve epoch (eğitim döngüsü) sayısı gibi parametrelerin farklı kombinasyonlarını denedim. Yaptığım iterasyonlar sonucunda modelin gereksiz yere hata vermesini (False Positive Rate) en aza indiren ve anomali yakalama yeteneğini maksimize eden en ideal model ağırlık (weight) setini bularak sisteme entegre ettim.",

    r"Yerel LLM \(Ollama\) servisinin yoğunluk veya çökme durumlarında sistemin kilitlenmemesi için bir Fallback \(Yedek\) mekanizması tasarladım\. LLM'den yanıt alınamadığı senaryolarda sistemin çökmesini önleyerek kural tabanlı \(Rule-based\) varsayılan uyarı mesajlarını devreye sokan güvenli bir yapı kurdum\.":
    "Sistemde görev yapan ve çözüm önerileri üreten Ollama/Qwen yerel Büyük Dil Modelinin (LLM), yüksek CPU tüketimi veya bellek yetersizliği sebebiyle çökmesi ya da aşırı yavaşlaması riskine karşı sistemin işleyişini garanti altına alacak bir 'Fallback' (Yedekleme ve Geri Çekilme) mimarisi tasarladım. Yazılımın LLM'e attığı isteğin belirli bir zaman aşımı (timeout) süresini geçmesi halinde kodun kilitlenmesini (blocking) engelleyen ve o an için model yerine kural tabanlı (Rule-based) klasik varsayılan uyarı/çözüm metinlerini devreye sokan hata toleranslı (Fault Tolerant) bir karar destek mekanizması kurdum.",

    r"Projenin farklı ortamlarda \(development, test, production\) hiçbir bağımlılık sorunu yaşamadan çalışabilmesi için Docker konteyner mimarisini inceledim\. FastAPI sunucusu, Agent ve Ollama servislerinin tek bir merkezden ayağa kaldırılabilmesi için Dockerfile yapılandırmaları üzerinde çalıştım\.":
    "Yazdığım uygulamanın benim bilgisayarım dışında herhangi bir sunucuda veya bulut ortamında (Cloud) 'Benim makinemde çalışıyordu' klasik problemi yaşanmadan, izole ve pürüzsüz bir biçimde çalışabilmesi için Docker tabanlı konteynerleştirme (Containerization) teknolojisini derinlemesine inceledim. Projenin ana bileşenleri olan FastAPI arka uç sunucusu, veri toplayan Agent servisi ve web arayüzü (Streamlit) için ayrı ayrı `Dockerfile` yapılandırmaları oluşturdum. Bu servislerin kendi içlerinde haberleşmesi için uygun ağ (network) ve port konfigürasyonlarını planlayarak, DevOps kültürünün temel taşlarından biri olan 'Infrastructure as Code' konseptine pratik bir giriş yaptım.",

    r"Projenin kod kalitesini ve test yeterliliğini somut bir metrikle ölçmek için pytest-cov kütüphanesini kullanarak Test Coverage analizi gerçekleştirdim\. Kritik iş mantığı sınıflarının \(Use Cases\) ve Pydantic şemalarının test edilme oranının %97 ila %100 arasında olduğunu raporladım\.":
    "Yazılım mühendisliğinde kod güvenilirliğinin en büyük ispatlarından biri olan Test Kapsamı (Test Coverage) üzerine yoğunlaştım. Yazdığım tüm entegrasyon ve birim (unit) testlerinin, kaynak kodun tam olarak yüzde kaçını çalıştırdığını sayısal ve somut bir metrik olarak görmek adına `pytest-cov` kütüphanesini kullanarak detaylı analiz raporları çıkardım. Çıkan rapor sonuçlarına göre, uygulamanın kalbini oluşturan kritik iş mantığı (Use Cases) sınıflarının, veritabanı etkileşimlerinin ve Pydantic validasyon şemalarının test edilme oranının %97 ile %100 arasına ulaştığını belgeleyerek kurumsal kalite standartlarını yakaladım.",

    r"Stajın son aşamasına yaklaşırken tüm kod tabanını gözden geçirerek \(Code Review\) performans iyileştirmeleri yaptım\. Bellek sızıntısı yaratan gereksiz nesne tutulumlarını temizledim, asenkron fonksiyon bloklarını optimize ettim ve veritabanı sorgularının hızını artırdım\.":
    "Staj programımın teslim ve kapanış aşamasına adım atarken, yazılım yaşam döngüsünün ayrılmaz bir parçası olan kod gözden geçirme (Code Review) ve teknik borç ödeme (Refactoring) çalışmalarına odaklandım. Sistem performansını düşürebilecek gereksiz döngüleri, bellekte fazladan yer tutan referansları ve asenkron I/O beklemelerini optimize ettim. Ayrıca, SQLite veritabanı üzerindeki okuma/yazma (CRUD) işlemlerinin hızını artırmak amacıyla bazı tablolara indeksleme stratejileri düşünerek genel uygulama verimliliğini hatırı sayılır oranda yukarı çektim.",

    r"Stajımın son gününde tüm sistemi \(Agent, FastAPI Backend, SQLite DB, PyTorch AI Model, Ollama LLM, Streamlit Dashboard\) aynı anda ayağa kaldırarak uçtan uca bir kaos ve anomali tespiti demosu gerçekleştirdim\. Kasıtlı bellek sızıntısı tetikleyerek sistemin bunu saniyeler içinde algılamasını, PyTorch ile sınıflandırmasını, LLM ile Türkçe çözüm üretmesini ve dashboard'da sergilemesini mentörümün katılımıyla başarıyla sundum\. Staj raporumu ve defterimi son kontrollerini yaparak tamamladım\.":
    "Stajımın son ve en heyecan verici gününde, haftalardır parça parça inşa ettiğim tüm bu devasa ekosistemi (Agent, FastAPI Backend, SQLite DB, PyTorch AI Model, Ollama LLM, Streamlit Dashboard) tam bir orkestra gibi aynı anda ayağa kaldırarak uçtan uca interaktif bir kaos ve anomali tespiti demosu (Live Demo) gerçekleştirdim. Arayüz üzerinden kasıtlı olarak bir bellek sızıntısı saldırısı başlatıp, sistemin bunu birkaç saniye içerisinde yakalamasını, PyTorch yapay sinir ağıyla doğru bir şekilde sınıflandırmasını, entegre yerel LLM üzerinden sistem yöneticisi için profesyonel bir Türkçe çözüm metni üretmesini ve tüm bu serüvenin dashboard'da kırmızı alarmlarla sergilenmesini mentörümün ve yöneticilerimin katılımıyla başarıyla canlı olarak sundum. Akabinde staj raporumu ve belgelerimi teslim ederek süreci gururla tamamladım."
}

for old_text, new_text in replacements.items():
    content = re.sub(old_text, new_text, content)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Done")
